<Project>
  <PropertyGroup>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)version.txt').Trim())</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <Authors>imevul</Authors>
    <Company>evu</Company>
    <Copyright>Copyright (c) 2026 imevul</Copyright>
    <Product>EvuMinimap</Product>
    <Description>Client-side Valheim minimap size and position.</Description>
    <RepositoryUrl>https://github.com/EvuMods/EvuMinimap</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RefsDir Condition="'$(RefsDir)' == ''">$(MSBuildThisFileDirectory).refs</RefsDir>
    <ValheimManaged>$(RefsDir)/Valheim</ValheimManaged>
    <BepInExCore>$(RefsDir)/BepInEx</BepInExCore>
  </PropertyGroup>
</Project>
